### ISSUE TITLE
concept

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedCommandBlock#1]
RedCommandBlock
================

Config:
-------

```
command-whitelist:
  enable: true
  world:
  - *
  list:
  - teleport
  - tp
```

1. Funktion: Command-Whitelist

Ist dieses Element aktiviert werden in den jeweilligen Welten nur die
CommandBlock-Befehle ausgeführt, die in der Config angegeben sind (command-whitelist.list).

**Comment by RedstoneFuture** [comment]
@Phoenix616

**Comment by Phoenix616** [comment]
Wäre eine Liste pro Welt nicht ein praktischeres Config Design? Zb: so:

```yaml
weltname:
- befehl1
- befehl2
welt2:
- befehl2
- befehl3
```
So kann man verschiedene Befehle pro Welt freigeben je nachdem welche was braucht.
